export const PALETTES = [
  {
    id: 'pequod',
    name: 'The Pequod',
    desc: 'gold on obsidian',
    bg: '#0c1014',
    dots: '#c8a96e',
    corner: '#c8a96e',
  },
  {
    id: 'white-whale',
    name: 'White Whale',
    desc: 'ivory on midnight',
    bg: '#0e1520',
    dots: '#f2ede4',
    corner: '#ddd4c2',
  },
  {
    id: 'hellfire',
    name: 'Hellfire',
    desc: 'crimson on char',
    bg: '#0c0808',
    dots: '#c1372a',
    corner: '#8b2020',
  },
  {
    id: 'leviathan',
    name: 'The Leviathan',
    desc: 'ocean on abyss',
    bg: '#020d18',
    dots: '#2a7ec4',
    corner: '#1a5d9c',
  },
  {
    id: 'ambergris',
    name: 'Ambergris',
    desc: 'amber on pitch',
    bg: '#100d06',
    dots: '#e8a930',
    corner: '#c48a1a',
  },
  {
    id: 'greenland',
    name: 'Greenland Sea',
    desc: 'seafoam on dark',
    bg: '#051410',
    dots: '#4caf75',
    corner: '#3a8c5c',
  },
  {
    id: 'nantucket',
    name: 'Nantucket Fog',
    desc: 'violet on dusk',
    bg: '#0d0b14',
    dots: '#9b7ecb',
    corner: '#7a5eab',
  },
  {
    id: 'styx',
    name: 'River Styx',
    desc: 'ice on deep',
    bg: '#050a14',
    dots: '#5cb8e8',
    corner: '#3a9bc8',
  },
];
